import React, {useState} from 'react';
import Head from "next/head";
import Layout from "@/layout";
import {Anchor, Breadcrumbs, Button, Container, Flex, Paper, SimpleGrid, Stack, Switch, Text, Title} from "@mantine/core";
import {PATH_DASHBOARD} from "@/routes";
import {PricingCard} from "@/components";

const items = [
    {title: 'Dashboard', href: PATH_DASHBOARD.default},
    {title: 'Pages', href: '#'},
    {title: 'Blank', href: '#'},
].map((item, index) => (
    <Anchor href={item.href} key={index}>
        {item.title}
    </Anchor>
));

function Pricing() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Layout>
                <Container>
                    <Stack>
                        <Title>Settings</Title>
                        <Breadcrumbs>{items}</Breadcrumbs>
                    </Stack>
                    <Paper>
                        <Title>Empty card header</Title>
                        <Text>Empty card text</Text>
                    </Paper>
                </Container>
            </Layout>
        </>
    );
}

export default Pricing;
