import React from 'react';
import Head from "next/head";
import Layout from "@/layout";
import {
    ActionIcon,
    Anchor,
    Box,
    Breadcrumbs,
    Container,
    Divider,
    Flex,
    Grid,
    Paper,
    rem,
    ScrollArea,
    Stack,
    TextInput,
    Title, useMantineTheme
} from "@mantine/core";
import {PATH_DASHBOARD} from "@/routes";
import {ChatItem, ChatsList} from "@/components";
import {IconSearch, IconSend} from "@tabler/icons-react";
import ChatsListData from "../../mocks/ChatsList.json"
import ChatItemsData from "../../mocks/ChatItems.json"

const items = [
    {title: 'Dashboard', href: PATH_DASHBOARD.default},
    {title: 'Pages', href: '#'},
    {title: 'Chat', href: '#'},
].map((item, index) => (
    <Anchor href={item.href} key={index}>
        {item.title}
    </Anchor>
));

const ICON_SIZE = 18;

function Chat() {
    const theme = useMantineTheme()

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Layout>
                <Container fluid>
                    <Stack>
                        <Title>Settings</Title>
                        <Breadcrumbs>{items}</Breadcrumbs>
                    </Stack>
                    <Paper component="div" sx={{height: rem(500)}}>
                        <Grid>
                            <Grid.Col lg={3}>
                                <Stack>
                                    <Box>
                                        <TextInput
                                            aria-label="search contact"
                                            placeholder="search contacts"
                                            icon={<IconSearch size={14}/>}
                                        />
                                    </Box>
                                    <Divider/>
                                    <Stack spacing={0}>
                                        {ChatsListData.map(c => <ChatsList
                                                key={c.id}
                                                lastMessage={c.last_message}
                                                firstName={c.first_name}
                                                lastName={c.last_name}
                                                avatar={c.avatar}
                                            />
                                        )}
                                    </Stack>
                                </Stack>
                            </Grid.Col>
                            <Grid.Col lg={9}>
                                <Box sx={{borderLeft: `1px solid ${theme.colors.gray[4]}`}}>
                                    <ScrollArea h={450}>
                                        <Stack>
                                            {ChatItemsData.map(c =>
                                                <ChatItem
                                                    key={c.id}
                                                    avatar={c.avatar}
                                                    id={c.id}
                                                    message={c.message}
                                                    fullName={c.sender ? 'you' : `${c?.first_name} ${c.last_name}`}
                                                    sender={c.sender}
                                                    sent_time={c.sent_time}
                                                    ml={c.sender ? 'auto' : 0}
                                                    sx={{maxWidth: '75%'}}
                                                />
                                            )}
                                        </Stack>
                                    </ScrollArea>
                                    <Divider/>
                                    <Paper>
                                        <Flex>
                                            <TextInput aria-label="message" placeholder="Type your message"/>
                                            <ActionIcon>
                                                <IconSend/>
                                            </ActionIcon>
                                        </Flex>
                                    </Paper>
                                </Box>
                            </Grid.Col>
                        </Grid>
                    </Paper>
                </Container>
            </Layout>
        </>
    );
}

export default Chat;
