import React, {useState} from 'react';
import Head from "next/head";
import {Anchor, Breadcrumbs, Button, Container, Flex, Paper, SimpleGrid, Stack, Switch, Text, Title} from "@mantine/core";
import {PATH_DASHBOARD} from "@/routes";
import {PricingCard} from "@/components";
import {AppLayout} from "@/layout";

const items = [
    {title: 'Dashboard', href: PATH_DASHBOARD.default},
    {title: 'Pages', href: '#'},
    {title: 'Pricing', href: '#'},
].map((item, index) => (
    <Anchor href={item.href} key={index}>
        {item.title}
    </Anchor>
));

const ICON_SIZE = 18;

const pricing = [
    {
        tier: 'basic',
        price: {
            month: 0,
            year: 0
        },
        features: ['Rich landing pages', '100+ components'],
        preferred: false,
        actionText: 'start for free'
    },
    {
        tier: 'standard',
        price: {
            month: 25,
            year: 45
        },
        features: ['Rich landing pages', '100+ components', 'Flexible licensing', 'Speedy build tooling', '6 months free support'],
        preferred: true,
        actionText: 'start with standard'
    },
    {
        tier: 'premium',
        price: {
            month: 40,
            year: 70
        },
        features: ['Rich landing pages', '100+ components', 'Flexible licensing', 'Speedy build tooling', '6 months free support', '256-bit encryption', 'Guaranteed 100% uptime', 'Unlimited users'],
        preferred: false,
        actionText: 'start with premium'
    },
]

function Pricing() {
    const [checked, setChecked] = useState(false);
    const pricingItems = pricing.map(p => <PricingCard monthly={checked} {...p}/>)

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <AppLayout>
                <Container>
                    <Stack>
                        <Title>Settings</Title>
                        <Breadcrumbs>{items}</Breadcrumbs>
                    </Stack>
                    <Paper>
                        <Title>Simple, fair pricing.</Title>
                        <Text>All types of businesses need access to development resources, so we give you the option to
                            decide how much you need to use.</Text>
                        <Flex>
                            <Text>Annual</Text>
                            <Switch
                                size="md"
                                checked={checked}
                                onChange={(event) => setChecked(event.currentTarget.checked)}
                            />
                            <Text>Monthly</Text>
                        </Flex>
                    </Paper>
                    <SimpleGrid cols={3}>{pricingItems}</SimpleGrid>
                    <Paper>
                        <Text>Need a more custom package?</Text>
                        <Button>Contact Us</Button>
                    </Paper>
                </Container>
            </AppLayout>
        </>
    );
}

export default Pricing;
