import React from 'react';
import Head from "next/head";
import Layout from "@/layout";
import {
    Anchor,
    Badge,
    Breadcrumbs,
    Container,
    Divider, Flex,
    Grid,
    Group,
    Paper, Progress,
    SimpleGrid,
    Stack,
    Text,
    Title
} from "@mantine/core";
import {PATH_DASHBOARD} from "@/routes";
import {ProjectsTable, RevenueChart, StatsCard, UserProfileCard} from "@/components";
import UserData from "../../mocks/UserProfile.json";
import {
    IconBrandFacebook,
    IconBrandGithub,
    IconBrandLinkedin,
    IconBrandTwitter, IconCurrencyDollar,
    IconHome,
    IconMapPinFilled, IconShoppingCartPlus
} from "@tabler/icons-react";
import StatsData from "@/mocks/StatsGrid.json";
import ProjectsData from "@/mocks/Projects.json";

const items = [
    {title: 'Dashboard', href: PATH_DASHBOARD.default},
    {title: 'Pages', href: '#'},
    {title: 'Profile', href: '#'},
].map((item, index) => (
    <Anchor href={item.href} key={index}>
        {item.title}
    </Anchor>
));

const ICON_SIZE = 18;

const skills = ['React', 'Mantine', 'Figma', 'Bootstrap', 'Typescript', 'Sass/SCSS']

function Profile() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Layout>
                <Container>
                    <Stack>
                        <Title>Profile</Title>
                        <Breadcrumbs>{items}</Breadcrumbs>
                    </Stack>
                    <Divider/>
                    <Grid>
                        <Grid.Col lg={3}>
                            <Stack>
                                <UserProfileCard data={UserData}/>
                                <Paper>
                                    <Title>Skills</Title>
                                    <Group spacing={4}>
                                        {skills.map(s => <Badge key={s}>{s}</Badge>)}
                                    </Group>
                                </Paper>
                                <Paper>
                                    <Stack>
                                        <Title>About</Title>
                                        <Group>
                                            <IconHome size={ICON_SIZE}/>
                                            <Text>Lives in Nairobi, Kenya</Text>
                                        </Group>
                                        <Group>
                                            <IconMapPinFilled size={ICON_SIZE}/>
                                            <Text>Works at Mantine</Text>
                                        </Group>
                                    </Stack>
                                </Paper>
                                <Paper>
                                    <Stack>
                                        <Title>Social</Title>
                                        <Group>
                                            <IconBrandFacebook size={ICON_SIZE}/>
                                            <Text component="a"
                                                  href="https://www.facebook.com/kelvinkk96">Facebook</Text>
                                        </Group>
                                        <Group>
                                            <IconBrandTwitter size={ICON_SIZE}/>
                                            <Text component="a" href="https://twitter.com/kelvink_96">Twitter</Text>
                                        </Group>
                                        <Group>
                                            <IconBrandLinkedin size={ICON_SIZE}/>
                                            <Text component="a"
                                                  href="https://www.linkedin.com/in/kelvink96/">LinkedIn</Text>
                                        </Group>
                                        <Group>
                                            <IconBrandGithub size={ICON_SIZE}/>
                                            <Text component="a" href="https://github.com/kelvink96">Github</Text>
                                        </Group>
                                    </Stack>
                                </Paper>
                            </Stack>
                        </Grid.Col>
                        <Grid.Col lg={9}>
                            <Stack>
                                <RevenueChart/>
                                <SimpleGrid cols={3}>
                                    <Paper>
                                        <Flex align="center" justify="space-between">
                                            <Stack>
                                                <Text>$ 81314</Text>
                                                <Text>Total earnings</Text>
                                            </Stack>
                                            <IconCurrencyDollar/>
                                        </Flex>
                                        <Progress value={32}/>
                                    </Paper>
                                    <Paper>
                                        <Flex align="center" justify="space-between">
                                            <Stack>
                                                <Text>2532</Text>
                                                <Text>Today's orders</Text>
                                            </Stack>
                                            <IconShoppingCartPlus/>
                                        </Flex>
                                        <Progress value={32}/>
                                    </Paper>
                                    <Paper>
                                        <Flex align="center" justify="space-between">
                                            <Stack>
                                                <Text>$ 97219</Text>
                                                <Text>Total revenue</Text>
                                            </Stack>
                                            <IconCurrencyDollar/>
                                        </Flex>
                                        <Progress value={32}/>
                                    </Paper>
                                </SimpleGrid>
                                <Paper>
                                    <Title>Projects</Title>
                                    <ProjectsTable data={ProjectsData.slice(0, 6)}/>
                                </Paper>
                            </Stack>
                        </Grid.Col>
                    </Grid>
                </Container>
            </Layout>
        </>
    );
}

export default Profile;
