import React, {useState} from 'react';
import Head from "next/head";
import {
    Anchor,
    Breadcrumbs,
    Button,
    Container,
    FileButton,
    Grid,
    Group,
    Image,
    Paper,
    Stack,
    Text,
    Textarea,
    TextInput,
    Title
} from "@mantine/core";
import {PATH_DASHBOARD} from "@/routes";
import {useForm} from "@mantine/form";
import {IconCloudUpload} from "@tabler/icons-react";
import {AppLayout} from "@/layout";

const items = [
    {title: 'Dashboard', href: PATH_DASHBOARD.default},
    {title: 'Pages', href: '#'},
    {title: 'Settings', href: '#'},
].map((item, index) => (
    <Anchor href={item.href} key={index}>
        {item.title}
    </Anchor>
));

const ICON_SIZE = 18;

function Settings() {
    const [file, setFile] = useState<File | null>(null);
    const accountForm = useForm({
        initialValues: {
            username: 'kelvinkiprop',
            biograghy: 'I\'m a software engineering graduate with a passion for transforming ideas into simple applications. I love experimenting with new technologies. Right now, I\'m working on building and shipping business automation solutions at Alternate Limited.\n',
        },
    });
    const accountInfoForm = useForm({
        initialValues: {
            firstname: 'kelvin',
            lastname: 'kiprop',
            email: 'kelvin.kiprop96@gmail.com',
            address: '',
            apartment: '',
            city: '',
            state: '',
            zip: ''
        },
    });

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <AppLayout>
                <Container>
                    <Stack>
                        <Title>Settings</Title>
                        <Breadcrumbs>{items}</Breadcrumbs>
                    </Stack>
                    <Paper>
                        <Title>User information</Title>
                        <Grid>
                            <Grid.Col lg={9}>
                                <Stack>
                                    <TextInput
                                        label="User Name"
                                        placeholder="user name" {...accountForm.getInputProps('username')}
                                    />
                                    <Textarea
                                        mt="md"
                                        label="Biography"
                                        placeholder="Biography"
                                        minRows={4}
                                        {...accountForm.getInputProps('biograghy')}
                                    />
                                    <Button sx={{width: 'fit-content'}}>Save Changes</Button>
                                </Stack>
                            </Grid.Col>
                            <Grid.Col lg={3}>
                                <Stack align="center">
                                    <Image
                                        src="https://res-console.cloudinary.com/ddh7hfzso/thumbnails/transform/v1/image/upload/Yl9hdXRvOnByZWRvbWluYW50LGNfcGFkLGhfMzAwLHdfMzAwLGZfanBnLGZsX2xvc3N5LmFueV9mb3JtYXQucHJlc2VydmVfdHJhbnNwYXJlbmN5LnByb2dyZXNzaXZl/v1/bWUvdjB6Y2RybWY2bXl3NzVlaGlqa2I=/template_primary"
                                        height={120}
                                        width={120}
                                        radius="50%"
                                    />
                                    <FileButton onChange={setFile} accept="image/png,image/jpeg">
                                        {(props) =>
                                            <Button
                                                {...props}
                                                leftIcon={<IconCloudUpload size={ICON_SIZE}/>}
                                            >
                                                Upload image
                                            </Button>
                                        }
                                    </FileButton>
                                    <Text align="center" size="xs" color="dimmed">For best results, use an image at
                                        least 128px by 128px in .jpg format</Text>
                                </Stack>
                            </Grid.Col>
                        </Grid>
                    </Paper>
                    <Paper>
                        <Stack>
                            <Title>Account information</Title>
                            <Group grow>
                                <TextInput
                                    label="First name"
                                    placeholder="first name" {...accountInfoForm.getInputProps('firstname')}
                                />
                                <TextInput
                                    label="Last name"
                                    placeholder="last name" {...accountInfoForm.getInputProps('lastname')}
                                />
                            </Group>
                            <TextInput
                                label="Email"
                                placeholder="email" {...accountInfoForm.getInputProps('email')}
                            />
                            <TextInput
                                label="Address"
                                placeholder="address" {...accountInfoForm.getInputProps('address')}
                            />
                            <TextInput
                                label="Apartment/Studio/Floor"
                                placeholder="apartment, studio, or floor" {...accountInfoForm.getInputProps('apartment')}
                            />
                            <Group grow>
                                <TextInput
                                    label="City"
                                    placeholder="city" {...accountInfoForm.getInputProps('city')}
                                />
                                <TextInput
                                    label="State"
                                    placeholder="state" {...accountInfoForm.getInputProps('state')}
                                />
                                <TextInput
                                    label="Zip"
                                    placeholder="zip" {...accountInfoForm.getInputProps('zip')}
                                />
                            </Group>
                            <Button>Save changes</Button>
                        </Stack>
                    </Paper>
                </Container>
            </AppLayout>
        </>
    );
}

export default Settings;
