import React, {useEffect, useState} from 'react';
import Head from "next/head";
import {AppLayout} from "@/layout";
import {Anchor, Breadcrumbs, Button, Container, Flex, Paper, Stack, Title} from "@mantine/core";
import {IconPlus} from "@tabler/icons-react";
import {InvoiceDetailsCard, InvoicesTable} from "@/components";
import InvoicesData from "@/mocks/Invoices.json";
import {PATH_DASHBOARD, PATH_INVOICES} from "@/routes";
import {useRouter} from "next/router";
import {Invoices} from "@/types";

const items = [
    {title: 'Dashboard', href: PATH_DASHBOARD.default},
    {title: 'Pages', href: '#'},
    {title: 'Invoices', href: PATH_INVOICES.invoices.all},
    {title: 'Details', href: '#'},
].map((item, index) => (
    <Anchor href={item.href} key={index}>
        {item.title}
    </Anchor>
));

function InvoiceDetails() {
    const router = useRouter()
    const [selectedData, setSelectedData] = useState<Invoices>();

    useEffect(() => {
        setSelectedData(InvoicesData.find(_ => _.id === router.query.id))
    }, [router, InvoicesData]);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <AppLayout>
                <Container>
                    <Flex>
                        <Stack>
                            <Title>Settings</Title>
                            <Breadcrumbs>{items}</Breadcrumbs>
                        </Stack>
                        <Button leftIcon={<IconPlus size={18}/>}>New Invoice</Button>
                    </Flex>
                    <Paper>
                        <Title>Invoices</Title>
                        <InvoiceDetailsCard data={selectedData}/>
                    </Paper>
                </Container>
            </AppLayout>
        </>
    );
}

export default InvoiceDetails;
