import React from 'react';
import Head from "next/head";
import Layout from "@/layout";
import {Anchor, Breadcrumbs, Button, Container, Flex, Paper, Stack, Title} from "@mantine/core";
import {PATH_DASHBOARD} from "@/routes";
import {InvoicesTable} from "@/components";
import InvoicesData from "../../mocks/Invoices.json";
import {IconPlus} from "@tabler/icons-react";

const items = [
    {title: 'Dashboard', href: PATH_DASHBOARD.default},
    {title: 'Pages', href: '#'},
    {title: 'Invoices', href: '#'},
].map((item, index) => (
    <Anchor href={item.href} key={index}>
        {item.title}
    </Anchor>
));

function List() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Layout>
                <Container>
                    <Flex>
                        <Stack>
                            <Title>Settings</Title>
                            <Breadcrumbs>{items}</Breadcrumbs>
                        </Stack>
                        <Button leftIcon={<IconPlus size={18}/>}>New Invoice</Button>
                    </Flex>
                    <Paper>
                        <Title>Invoices</Title>
                        <InvoicesTable data={InvoicesData}/>
                    </Paper>
                </Container>
            </Layout>
        </>
    );
}

export default List;
