/**
 * Code generated by `scripts/generate-dto.mjs`. Do not edit by hand.
 *
 * One interface per mock fixture behind a dashboard endpoint, inferred from the
 * fixture itself. `src/test/generated-dto.test.ts` asserts every row of every
 * fixture is assignable to the matching type and that every dashboard endpoint
 * has one, so a mock edit that changes shape fails the suite rather than
 * diverging from the code.
 *
 * Regenerate with: node scripts/generate-dto.mjs
 */

import type { CoreStatsDto } from './dashboard';

/** `crm-activities.json` - served by `/api/crm/activities`. */
export interface CrmActivitiesDto {
  id: number;
  type: string;
  company: string;
  contact: string;
  description: string;
  assignedTo: string;
  timestamp: string;
  status: string;
}

/** `deals.json` - served by `/api/crm/deals`. */
export interface DealsDto {
  id: number;
  company: string;
  contact: string;
  email: string;
  value: number;
  stage: string;
  probability: number;
  expectedCloseDate: string;
  assignedTo: string;
  lastActivity: string;
}

/** `leads.json` - served by `/api/crm/leads`. */
export interface LeadsDto {
  stage: string;
  count: number;
  value: number;
  percentage: number;
  color: string;
}

/** `crm-stats.json` - served by `/api/crm/stats`. */
export interface CrmStatsDto {
  title: string;
  value: string;
  diff: number;
  period: string;
  icon: string;
  color: string;
}

/** `revenue-by-category.json` - served by `/api/ecommerce/categories`. */
export interface RevenueByCategoryDto {
  category: string;
  revenue: number;
  orders: number;
  percentage: number;
  color: string;
}

/** `order-status.json` - served by `/api/ecommerce/orders`. */
export interface OrderStatusDto {
  status: string;
  count: number;
  value: number;
  percentage: number;
  color: string;
}

/** `top-products.json` - served by `/api/ecommerce/products`. */
export interface TopProductsDto {
  id: number;
  name: string;
  sku: string;
  category: string;
  price: number;
  sales: number;
  revenue: number;
  stock: number;
  image: string;
  trend: string;
}

/** `ecommerce-stats.json` - served by `/api/ecommerce/stats`. */
export interface EcommerceStatsDto {
  title: string;
  value: string;
  diff: number;
  period: string;
  icon: string;
  color: string;
}

/** `student-activity.json` - served by `/api/education/activity`. */
export interface StudentActivityDto {
  day: string;
  logins: number;
  assignmentsSubmitted: number;
  forumPosts: number;
}

/** `course-completion.json` - served by `/api/education/courses`. */
export interface CourseCompletionDto {
  id: number;
  courseName: string;
  courseCode: string;
  instructor: string;
  enrolledStudents: number;
  completedStudents: number;
  inProgress: number;
  dropped: number;
  completionRate: number;
  averageGrade: string;
  category: string;
}

/** `student-enrollment.json` - served by `/api/education/enrollment`. */
export interface StudentEnrollmentDto {
  month: string;
  newStudents: number;
  activeStudents: number;
  dropouts: number;
}

/** `grade-distribution.json` - served by `/api/education/grades`. */
export interface GradeDistributionDto {
  name: string;
  value: number;
  students: number;
  color: string;
}

/** `instructor-performance.json` - served by `/api/education/instructors`. */
export interface InstructorPerformanceDto {
  id: number;
  instructorName: string;
  department: string;
  coursesTeaching: number;
  totalStudents: number;
  averageRating: number;
  completionRate: number;
  responseTime: string;
  status: string;
}

/** `education-stats.json` - served by `/api/education/stats`. */
export interface EducationStatsDto {
  title: string;
  value: string;
  diff: number;
  period: string;
  icon: string;
  color: string;
}

/** `cashflow.json` - served by `/api/finance/cashflow`. */
export interface CashflowDto {
  month: string;
  income: number;
  expenses: number;
  netCashflow: number;
}

/** `expenses.json` - served by `/api/finance/expenses`. */
export interface ExpensesDto {
  category: string;
  amount: number;
  percentage: number;
  color: string;
  trend: number;
}

/** `invoices-finance.json` - served by `/api/finance/invoices`. */
export interface InvoicesFinanceDto {
  id: number;
  invoiceNumber: string;
  client: string;
  amount: number;
  issueDate: string;
  dueDate: string;
  status: string;
  paymentDate: string | null;
}

/** `finance-stats.json` - served by `/api/finance/stats`. */
export interface FinanceStatsDto {
  title: string;
  value: string;
  diff: number;
  period: string;
  icon: string;
  color: string;
}

/** `patient-appointments.json` - served by `/api/healthcare/appointments`. */
export interface PatientAppointmentsDto {
  id: number;
  patientName: string;
  patientId: string;
  age: number;
  appointmentType: string;
  doctor: string;
  department: string;
  scheduledTime: string;
  status: string;
  priority: string;
}

/** `bed-occupancy.json` - served by `/api/healthcare/bed-occupancy`. */
export interface BedOccupancyDto {
  department: string;
  totalBeds: number;
  occupiedBeds: number;
  availableBeds: number;
  occupancyRate: number;
  criticalPatients: number;
  color: string;
}

/** `department-performance.json` - served by `/api/healthcare/departments`. */
export interface DepartmentPerformanceDto {
  name: string;
  value: number;
  patients: number;
  color: string;
}

/** `medical-inventory.json` - served by `/api/healthcare/inventory`. */
export interface MedicalInventoryDto {
  id: number;
  itemName: string;
  category: string;
  currentStock: number;
  minimumStock: number;
  maxStock: number;
  unitPrice: number;
  status: string;
  lastRestocked: string;
  supplier: string;
}

/** `patient-satisfaction.json` - served by `/api/healthcare/satisfaction`. */
export interface PatientSatisfactionDto {
  month: string;
  overall: number;
  treatment: number;
  staff: number;
  facilities: number;
}

/** `healthcare-stats.json` - served by `/api/healthcare/stats`. */
export interface HealthcareStatsDto {
  title: string;
  value: string;
  diff: number;
  period: string;
  icon: string;
  color: string;
}

/** `attendance-data.json` - served by `/api/hr/attendance`. */
export interface AttendanceDataDto {
  month: string;
  present: number;
  leave: number;
  absent: number;
}

/** `employee-distribution.json` - served by `/api/hr/employee-distribution`. */
export interface EmployeeDistributionDto {
  department: string;
  count: number;
  percentage: number;
  color: string;
}

/** `open-positions.json` - served by `/api/hr/open-positions`. */
export interface OpenPositionsDto {
  id: number;
  title: string;
  department: string;
  location: string;
  type: string;
  applicants: number;
  daysOpen: number;
  priority: string;
}

/** `employee-performance.json` - served by `/api/hr/performance`. */
export interface EmployeePerformanceDto {
  month: string;
  excellent: number;
  good: number;
  average: number;
  poor: number;
}

/** `recruitment-pipeline.json` - served by `/api/hr/recruitment-pipeline`. */
export interface RecruitmentPipelineDto {
  stage: string;
  count: number;
  color: string;
}

/** `hr-stats.json` - served by `/api/hr/stats`. */
export interface HrStatsDto {
  title: string;
  value: string;
  diff: number;
  icon: string;
  color: string;
}

/** `Languages.json` - served by `/api/languages`. */
export interface LanguagesDto {
  id: string;
  language: string;
  users: number;
  users_percentage: number;
}

/** `delivery-performance.json` - served by `/api/logistics/delivery-performance`. */
export interface DeliveryPerformanceDto {
  month: string;
  onTime: number;
  delayed: number;
  total: number;
}

/** `fleet-status.json` - served by `/api/logistics/fleet-status`. */
export interface FleetStatusDto {
  category: string;
  count: number;
  percentage: number;
  color: string;
}

/** `route-efficiency.json` - served by `/api/logistics/route-efficiency`. */
export interface RouteEfficiencyDto {
  route: string;
  efficiency: number;
  avgTime: string;
  shipments: number;
  fuelCost: string;
}

/** `active-shipments.json` - served by `/api/logistics/shipments`. */
export interface ActiveShipmentsDto {
  id: string;
  origin: string;
  destination: string;
  status: string;
  driver: string;
  progress: number;
  eta: string;
  weight: string;
  type: string;
}

/** `logistics-stats.json` - served by `/api/logistics/stats`. */
export interface LogisticsStatsDto {
  title: string;
  value: string;
  diff: number;
  icon: string;
  color: string;
}

/** `warehouse-inventory.json` - served by `/api/logistics/warehouse-inventory`. */
export interface WarehouseInventoryDto {
  warehouse: string;
  capacity: number;
  inbound: number;
  outbound: number;
  location: string;
}

/** `campaign-performance.json` - served by `/api/marketing/campaigns`. */
export interface CampaignPerformanceDto {
  date: string;
  impressions: number;
  clicks: number;
  conversions: number;
}

/** `email-campaigns.json` - served by `/api/marketing/email-campaigns`. */
export interface EmailCampaignsDto {
  id: number;
  campaignName: string;
  sentDate: string;
  recipients: number;
  opened: number;
  clicked: number;
  bounced: number;
  unsubscribed: number;
  openRate: number;
  clickRate: number;
  bounceRate: number;
  conversions: number;
}

/** `social-media-stats.json` - served by `/api/marketing/social-media`. */
export interface SocialMediaStatsDto {
  platform: string;
  followers: number;
  engagement: number;
  posts: number;
  reach: number;
  trend: string;
  color: string;
}

/** `marketing-stats.json` - served by `/api/marketing/stats`. */
export interface MarketingStatsDto {
  title: string;
  value: string;
  diff: number;
  period: string;
  icon: string;
  color: string;
}

/** `top-campaigns.json` - served by `/api/marketing/top-campaigns`. */
export interface TopCampaignsDto {
  id: number;
  name: string;
  type: string;
  budget: number;
  spent: number;
  roi: number;
  impressions: number;
  conversions: number;
  status: string;
}

/** `traffic-sources.json` - served by `/api/marketing/traffic-sources`. */
export interface TrafficSourcesDto {
  name: string;
  value: number;
  visitors: number;
  color: string;
}

/** `Projects.json` - served by `/api/projects`. */
export interface ProjectsDto {
  id: string;
  name: string;
  start_date: string;
  end_date: string;
  state: string;
  assignee: string;
}

/** `location-analytics.json` - served by `/api/real-estate/locations`. */
export interface LocationAnalyticsDto {
  location: string;
  properties: number;
  avgPrice: number;
  growth: number;
  occupancy: number;
}

/** `price-distribution.json` - served by `/api/real-estate/price-distribution`. */
export interface PriceDistributionDto {
  range: string;
  count: number;
  color: string;
}

/** `property-listings.json` - served by `/api/real-estate/properties`. */
export interface PropertyListingsDto {
  id: number;
  address: string;
  city: string;
  state: string;
  price: number;
  bedrooms: number;
  bathrooms: number;
  sqft: number;
  status: string;
  type: string;
  daysOnMarket: number;
}

/** `property-types.json` - served by `/api/real-estate/property-types`. */
export interface PropertyTypesDto {
  type: string;
  count: number;
  percentage: number;
  avgPrice: number;
  color: string;
}

/** `sales-trends.json` - served by `/api/real-estate/sales-trends`. */
export interface SalesTrendsDto {
  month: string;
  sales: number;
  revenue: number;
  avgPrice: number;
}

/** `real-estate-stats.json` - served by `/api/real-estate/stats`. */
export interface RealEstateStatsDto {
  title: string;
  value: string;
  diff: number;
  icon: string;
  color: string;
}

/** `Traffic.json` - served by `/api/traffic`. */
export interface TrafficDto {
  id: string;
  source: string;
  users: number;
  sessions: number;
  bounce_rate: number;
  avg_session_period: number;
}

/** Payload type per dashboard endpoint, for the page-level fetch hooks. */
export interface DashboardEndpointPayloads {
  '/api/crm/activities': CrmActivitiesDto[];
  '/api/crm/deals': DealsDto[];
  '/api/crm/leads': LeadsDto[];
  '/api/crm/stats': CrmStatsDto[];
  '/api/ecommerce/categories': RevenueByCategoryDto[];
  '/api/ecommerce/orders': OrderStatusDto[];
  '/api/ecommerce/products': TopProductsDto[];
  '/api/ecommerce/stats': EcommerceStatsDto[];
  '/api/education/activity': StudentActivityDto[];
  '/api/education/courses': CourseCompletionDto[];
  '/api/education/enrollment': StudentEnrollmentDto[];
  '/api/education/grades': GradeDistributionDto[];
  '/api/education/instructors': InstructorPerformanceDto[];
  '/api/education/stats': EducationStatsDto[];
  '/api/finance/cashflow': CashflowDto[];
  '/api/finance/expenses': ExpensesDto[];
  '/api/finance/invoices': InvoicesFinanceDto[];
  '/api/finance/stats': FinanceStatsDto[];
  '/api/healthcare/appointments': PatientAppointmentsDto[];
  '/api/healthcare/bed-occupancy': BedOccupancyDto[];
  '/api/healthcare/departments': DepartmentPerformanceDto[];
  '/api/healthcare/inventory': MedicalInventoryDto[];
  '/api/healthcare/satisfaction': PatientSatisfactionDto[];
  '/api/healthcare/stats': HealthcareStatsDto[];
  '/api/hr/attendance': AttendanceDataDto[];
  '/api/hr/employee-distribution': EmployeeDistributionDto[];
  '/api/hr/open-positions': OpenPositionsDto[];
  '/api/hr/performance': EmployeePerformanceDto[];
  '/api/hr/recruitment-pipeline': RecruitmentPipelineDto[];
  '/api/hr/stats': HrStatsDto[];
  '/api/languages': LanguagesDto[];
  '/api/logistics/delivery-performance': DeliveryPerformanceDto[];
  '/api/logistics/fleet-status': FleetStatusDto[];
  '/api/logistics/route-efficiency': RouteEfficiencyDto[];
  '/api/logistics/shipments': ActiveShipmentsDto[];
  '/api/logistics/stats': LogisticsStatsDto[];
  '/api/logistics/warehouse-inventory': WarehouseInventoryDto[];
  '/api/marketing/campaigns': CampaignPerformanceDto[];
  '/api/marketing/email-campaigns': EmailCampaignsDto[];
  '/api/marketing/social-media': SocialMediaStatsDto[];
  '/api/marketing/stats': MarketingStatsDto[];
  '/api/marketing/top-campaigns': TopCampaignsDto[];
  '/api/marketing/traffic-sources': TrafficSourcesDto[];
  '/api/projects': ProjectsDto[];
  '/api/real-estate/locations': LocationAnalyticsDto[];
  '/api/real-estate/price-distribution': PriceDistributionDto[];
  '/api/real-estate/properties': PropertyListingsDto[];
  '/api/real-estate/property-types': PropertyTypesDto[];
  '/api/real-estate/sales-trends': SalesTrendsDto[];
  '/api/real-estate/stats': RealEstateStatsDto[];
  '/api/stats': CoreStatsDto;
  '/api/traffic': TrafficDto[];
}

/** Every fixture-backed dashboard endpoint path. */
export type DashboardEndpoint = keyof DashboardEndpointPayloads;

/** Array-backed dashboard endpoints only; `/api/stats` is an object payload. */
export type ArrayBackedDashboardEndpoint = Exclude<
  DashboardEndpoint,
  '/api/stats'
>;

/**
 * The mock fixture each array-backed dashboard endpoint serves, at runtime.
 *
 * `src/test/generated-dto.test.ts` reads this to check every generated type
 * against the rows it describes, which is what stops the two drifting apart.
 */
export const DASHBOARD_ENDPOINT_FIXTURES = {
  '/api/crm/activities': 'crm-activities.json',
  '/api/crm/deals': 'deals.json',
  '/api/crm/leads': 'leads.json',
  '/api/crm/stats': 'crm-stats.json',
  '/api/ecommerce/categories': 'revenue-by-category.json',
  '/api/ecommerce/orders': 'order-status.json',
  '/api/ecommerce/products': 'top-products.json',
  '/api/ecommerce/stats': 'ecommerce-stats.json',
  '/api/education/activity': 'student-activity.json',
  '/api/education/courses': 'course-completion.json',
  '/api/education/enrollment': 'student-enrollment.json',
  '/api/education/grades': 'grade-distribution.json',
  '/api/education/instructors': 'instructor-performance.json',
  '/api/education/stats': 'education-stats.json',
  '/api/finance/cashflow': 'cashflow.json',
  '/api/finance/expenses': 'expenses.json',
  '/api/finance/invoices': 'invoices-finance.json',
  '/api/finance/stats': 'finance-stats.json',
  '/api/healthcare/appointments': 'patient-appointments.json',
  '/api/healthcare/bed-occupancy': 'bed-occupancy.json',
  '/api/healthcare/departments': 'department-performance.json',
  '/api/healthcare/inventory': 'medical-inventory.json',
  '/api/healthcare/satisfaction': 'patient-satisfaction.json',
  '/api/healthcare/stats': 'healthcare-stats.json',
  '/api/hr/attendance': 'attendance-data.json',
  '/api/hr/employee-distribution': 'employee-distribution.json',
  '/api/hr/open-positions': 'open-positions.json',
  '/api/hr/performance': 'employee-performance.json',
  '/api/hr/recruitment-pipeline': 'recruitment-pipeline.json',
  '/api/hr/stats': 'hr-stats.json',
  '/api/languages': 'Languages.json',
  '/api/logistics/delivery-performance': 'delivery-performance.json',
  '/api/logistics/fleet-status': 'fleet-status.json',
  '/api/logistics/route-efficiency': 'route-efficiency.json',
  '/api/logistics/shipments': 'active-shipments.json',
  '/api/logistics/stats': 'logistics-stats.json',
  '/api/logistics/warehouse-inventory': 'warehouse-inventory.json',
  '/api/marketing/campaigns': 'campaign-performance.json',
  '/api/marketing/email-campaigns': 'email-campaigns.json',
  '/api/marketing/social-media': 'social-media-stats.json',
  '/api/marketing/stats': 'marketing-stats.json',
  '/api/marketing/top-campaigns': 'top-campaigns.json',
  '/api/marketing/traffic-sources': 'traffic-sources.json',
  '/api/projects': 'Projects.json',
  '/api/real-estate/locations': 'location-analytics.json',
  '/api/real-estate/price-distribution': 'price-distribution.json',
  '/api/real-estate/properties': 'property-listings.json',
  '/api/real-estate/property-types': 'property-types.json',
  '/api/real-estate/sales-trends': 'sales-trends.json',
  '/api/real-estate/stats': 'real-estate-stats.json',
  '/api/traffic': 'Traffic.json',
} as const satisfies Record<ArrayBackedDashboardEndpoint, string>;
