import React from 'react';
import {
    Anchor,
    Button,
    Center,
    Checkbox,
    Group,
    Paper,
    PasswordInput,
    rem,
    Stack,
    Text,
    TextInput,
    Title
} from "@mantine/core";
import Head from "next/head";
import {IconLayout2} from "@tabler/icons-react";
import Link from "next/link";
import {PATH_AUTH, PATH_DASHBOARD} from "@/routes";

function Signin() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Center sx={{height: '100vh', width: '100vw'}}>
                <Stack>
                    <Center>
                        <IconLayout2 size={36} color="blue"/>
                    </Center>
                    <Title align="center">
                        Welcome back!
                    </Title>
                    <Text color="dimmed" align="center">Sign in to your account to continue</Text>

                    <Paper withBorder shadow="md" p={30} mt={15} radius="md" sx={{width: rem(420)}}>
                        <TextInput label="Email" placeholder="you@mantine.dev" required/>
                        <PasswordInput label="Password" placeholder="Your password" required mt="md"/>
                        <Group position="apart" mt="lg">
                            <Checkbox label="Remember me"/>
                            <Text component={Link} href={PATH_AUTH.passwordReset} size="sm">
                                Forgot password?
                            </Text>
                        </Group>
                        <Button fullWidth mt="xl" component={Link} href={PATH_DASHBOARD.default}>
                            Sign in
                        </Button>
                        <Text color="dimmed" size="sm" mt="md" align="center">
                            Do not have an account yet?{' '}
                            <Text size="sm" component={Link} href={PATH_AUTH.signup}>
                                Create account
                            </Text>
                        </Text>
                    </Paper>
                </Stack>
            </Center>
        </>
    );
}

export default Signin;
