import Head from 'next/head'
import {GuestLayout} from "@/layout";
import {Button} from "@mantine/core";
import Link from "next/link";
import {PATH_DASHBOARD} from "@/routes";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <GuestLayout>
                <Button component={Link} href={PATH_DASHBOARD.default}>Live Preview</Button>
            </GuestLayout>
        </>
    )
}
