import Head from 'next/head'
import {GuestLayout} from "@/layout";
import {
    Badge,
    Box,
    BoxProps,
    Button,
    Center,
    Container,
    createStyles,
    Flex,
    Grid,
    Group,
    Image,
    Paper,
    PaperProps,
    rem,
    SimpleGrid,
    Spoiler,
    Stack,
    Text,
    ThemeIcon,
    ThemeIconProps,
    Title,
    Tooltip, UnstyledButton, useMantineTheme
} from "@mantine/core";
import Link from "next/link";
import {PATH_DASHBOARD} from "@/routes";
import {
    IconAdjustmentsHorizontal, IconArrowRight, IconBook, IconChevronDown, IconChevronUp,
    IconColorSwatch,
    IconDevices,
    IconFolderCode,
    IconScaleOutline,
    IconSettingsCog
} from "@tabler/icons-react";
import React from "react";
import CountUp from "react-countup";
import {useMediaQuery} from "@mantine/hooks";

const useStyles = createStyles((theme) => ({
    hero: {
        backgroundColor: theme.black,
        color: theme.white,
        paddingTop: `calc(${theme.spacing.xl} * 4)`,
        paddingBottom: `calc(${theme.spacing.xl} * 4)`,
        paddingLeft: `calc(${theme.spacing.xl} * 4)`,
        paddingRight: `calc(${theme.spacing.xl} * 4)`,

        [theme.fn.smallerThan('sm')]: {
            paddingTop: `calc(${theme.spacing.xl})`,
            paddingBottom: `calc(${theme.spacing.xl})`,
            paddingLeft: `calc(${theme.spacing.xl})`,
            paddingRight: `calc(${theme.spacing.xl})`,
        },
    },
    title: {
        fontWeight: 800,
        fontSize: rem(40),
        letterSpacing: rem(-1),
        marginBottom: theme.spacing.xs,

        [theme.fn.smallerThan('xs')]: {
            fontSize: rem(28),
            textAlign: 'left',
        },
    },
    highlight: {
        color: theme.colors[theme.primaryColor][6],
    },
    stackControl: {
        textTransform: 'capitalize',
        backgroundColor: theme.colors.dark[6],
        color: theme.white,
        padding: `${rem(6)} ${rem(10)}`,
        borderRadius: theme.radius.md
    },
    variantImg: {
        maxHeight: rem(280),
        width: '100%',
        objectFit: 'contain',
    },
    variantTitle: {
        textAlign: 'center',
        marginTop: theme.spacing.md,
        fontWeight: 600
    }
}))

const TECH_STACK = [
    {title: 'nextjs', version: '13.14.12', href: 'https://nextjs.org/',},
    {title: 'react', version: '18.2.0', href: 'https://react.dev/',},
    {title: 'typescript', version: '5.1.6', href: 'https://www.typescriptlang.org/',},
    {title: 'mantine', version: '6.0.16', href: 'https://mantine.dev/'},
    {title: 'tabler icons', version: '2.28.0', href: 'https://tabler-icons.io/'},
    {title: 'tiptap', version: '2.28.0', href: 'https://tiptap.dev/'},
    {title: 'apexcharts', version: '3.41.0', href: 'https://apexcharts.com/'},
    {title: 'dayjs', version: '1.11.9', href: 'https://day.js.org/'},
    {title: 'fullcalendar', version: '6.1.8', href: 'https://fullcalendar.io/'},
    {title: 'emotion', version: '11.11.1', href: 'https://emotion.sh/docs/introduction'},
    {title: 'dnd-kit', version: '6.0.8', href: 'https://dndkit.com/'},
    {title: 'embla-carousel', version: '8.0.0', href: 'https://www.embla-carousel.com/'},
    {title: 'mantine datatable', version: '2.9.0', href: 'https://icflorescu.github.io/mantine-datatable'},
    {title: 'lodash', version: '4.17.21', href: 'https://lodash.com/'},
    {title: 'react simple maps', version: '3.0.0', href: 'https://www.react-simple-maps.io/'},
]

const PAPER_PROPS: PaperProps = {
    p: "md",
    shadow: "md",
    radius: "md",
    sx: {
        height: '100%',
        backgroundColor: 'transparent'
    }
}

const THEME_ICON_PROPS: Omit<ThemeIconProps, 'children'> = {
    variant: "light",
    size: 48
}

export default function Home() {
    const {classes, theme} = useStyles()
    const tablet_match = useMediaQuery('(max-width: 768px)');

    const IMAGE_PAPER_PROPS: PaperProps = {
        p: 'md',
        sx: {
            height: '100%',
            backgroundColor: 'transparent',

            '&:hover': {
                'img': {
                    boxShadow: theme.shadows.lg,
                    transition: 'all ease 150ms',
                    transform: 'scale(1.03)',
                }
            }
        }
    }

    const BOX_PROPS: BoxProps = {
        mt: 120,
        pb: 80,
        px: tablet_match ? 20 : 48,
    }

    return (
        <>
            <Head>
                <title>DesignSparx | Website UI Kit</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <GuestLayout>
                <Box className={classes.hero}>
                    <Grid>
                        <Grid.Col lg={6}>
                            <Stack>
                                <Text>Build like a Pro</Text>
                                <Title className={classes.title}>
                                    The simplest and fastest way to build your next{' '}
                                    <Text component="span" inherit className={classes.highlight}>
                                        Mantine UI{' '}
                                    </Text>
                                    dashboard or app.
                                </Title>
                                <Text>Design Sparx comes with hundreds of UI elements, forms, tables, charts, pages and
                                    icons that helps you to create your web apps or applications faster.</Text>
                                <Group my="lg">
                                    <Button
                                        component={Link}
                                        href={PATH_DASHBOARD.default}
                                        size="md"
                                        rightIcon={<IconArrowRight/>}
                                    >
                                        Live Demo
                                    </Button>
                                    <Button
                                        size="md"
                                        component="a"
                                        href="https://analytics-dashboard-docs.netlify.app/"
                                        target="_blank"
                                        variant="white"
                                    >
                                        Read Docs
                                    </Button>
                                </Group>
                                <Stack>
                                    <Text>Tech Stack:</Text>
                                    <Spoiler
                                        maxHeight={48}
                                        showLabel={
                                            <Button
                                                variant="default"
                                                compact
                                                leftIcon={<IconChevronDown size={12}/>}
                                            >
                                                Show more
                                            </Button>
                                        }
                                        hideLabel={
                                            <Button
                                                variant="default"
                                                compact
                                                mt="md"
                                                leftIcon={<IconChevronUp size={12}/>}
                                            >
                                                Hide
                                            </Button>
                                        }
                                    >
                                        <Group>
                                            {TECH_STACK.map(t =>
                                                <Tooltip key={t.title} label={`${t.title}-${t.version}`}>
                                                    <UnstyledButton
                                                        className={classes.stackControl} component="a"
                                                        href={t.href}
                                                        target="_blank"
                                                    >
                                                        {t.title}
                                                    </UnstyledButton>
                                                </Tooltip>
                                            )}
                                        </Group>
                                    </Spoiler>
                                </Stack>
                            </Stack>
                        </Grid.Col>
                        <Grid.Col lg={6}>
                            <Image
                                src="/thumbnail-img-b.jpg"
                                alt="/"
                            />
                        </Grid.Col>
                    </Grid>
                </Box>
                <Box {...BOX_PROPS}>
                    <Container size="lg">
                        <Title ta="center" order={2}>Carefully crafted components ready to use in your
                            project</Title>
                        <SimpleGrid
                            cols={4}
                            spacing="lg"
                            my="xl"
                            breakpoints={[
                                {maxWidth: 'md', cols: 2, spacing: 'md'},
                                {maxWidth: 'sm', cols: 1, spacing: 'sm'},
                            ]}
                        >
                            <Paper {...PAPER_PROPS}>
                                <Flex
                                    align="center"
                                    direction={{base: 'column', sm: 'row'}}
                                    gap={{base: 'sm', sm: 'lg'}}
                                    justify={{sm: 'center'}}
                                >
                                    <Title color="blue.7"><CountUp end={50}/>+</Title>
                                    <Text>Beautifully coded page examples</Text>
                                </Flex>
                            </Paper>
                            <Paper {...PAPER_PROPS}>
                                <Flex
                                    align="center"
                                    direction={{base: 'column', sm: 'row'}}
                                    gap={{base: 'sm', sm: 'lg'}}
                                    justify={{sm: 'center'}}
                                >
                                    <Title color="blue.7"><CountUp end={100}/>+</Title>
                                    <Text>Components and widgets</Text>
                                </Flex>
                            </Paper>
                            <Paper {...PAPER_PROPS}>
                                <Flex
                                    align="center"
                                    direction={{base: 'column', sm: 'row'}}
                                    gap={{base: 'sm', sm: 'lg'}}
                                    justify={{sm: 'center'}}
                                >
                                    <IconDevices size={50} color={theme.colors.blue[7]}/>
                                    <Text>Optimized to work for most devices</Text>
                                </Flex>
                            </Paper>
                            <Paper {...PAPER_PROPS}>
                                <Flex
                                    align="center"
                                    direction={{base: 'column', sm: 'row'}}
                                    gap={{base: 'sm', sm: 'lg'}}
                                    justify={{sm: 'center'}}
                                >
                                    <IconColorSwatch size={50} color={theme.colors.blue[7]}/>
                                    <Text>Customize it to meet your brand's identity</Text>
                                </Flex>
                            </Paper>
                        </SimpleGrid>
                    </Container>
                    <SimpleGrid
                        cols={3}
                        spacing="lg"
                        breakpoints={[
                            {maxWidth: 'md', cols: 2, spacing: 'md'},
                            {maxWidth: 'sm', cols: 1, spacing: 'sm'},
                        ]}
                    >
                        <Paper {...IMAGE_PAPER_PROPS}>
                            <Image src="/a-dashboard.png" className={classes.variantImg}/>
                            <Text className={classes.variantTitle}>Default variant</Text>
                        </Paper>
                        <Paper {...IMAGE_PAPER_PROPS}>
                            <Image src="/orders-pink.png" className={classes.variantImg}/>
                            <Text className={classes.variantTitle}>Pink variant</Text>
                        </Paper>
                        <Paper {...IMAGE_PAPER_PROPS}>
                            <Image src="/tasks-orange.png" className={classes.variantImg}/>
                            <Text className={classes.variantTitle}>Orange variant</Text>
                        </Paper>
                        <Paper {...IMAGE_PAPER_PROPS}>
                            <Image src="/profile-green.png" className={classes.variantImg}/>
                            <Text className={classes.variantTitle}>Green variant</Text>
                        </Paper>
                        <Paper {...IMAGE_PAPER_PROPS}>
                            <Image src="/chat-grape.png" className={classes.variantImg}/>
                            <Text className={classes.variantTitle}>Purple variant</Text>
                        </Paper>
                        <Paper {...IMAGE_PAPER_PROPS}>
                            <Image src="/s-dashboard-dark.png" className={classes.variantImg}/>
                            <Text className={classes.variantTitle}>Dark variant</Text>
                        </Paper>
                    </SimpleGrid>
                </Box>
                {/*<Box {...BOX_PROPS}>*/}
                {/*    <Title ta="center" mb="md" order={2}>We build it, you rock it!</Title>*/}
                {/*    <Text ta="center" mb="lg">Start focusing on your goals, by spending less time creating pages using*/}
                {/*        our examples.</Text>*/}
                {/*    <SimpleGrid cols={4}>*/}
                {/*        <Image src="/a-dashboard.png"/>*/}
                {/*        <Image src="/profile.png"/>*/}
                {/*        <Image src="/tasks.png"/>*/}
                {/*        <Image src="/invoices.png"/>*/}
                {/*    </SimpleGrid>*/}
                {/*</Box>*/}
                <Box {...BOX_PROPS}>
                    <Container size="lg">
                        <Badge size="lg" variant="filled" mb="md">Key features</Badge>
                        <Text mb="lg">Quick helps you build beautiful websites that stand out and automatically adapt to
                            your style.</Text>
                        <SimpleGrid
                            cols={4}
                            spacing="lg"
                            breakpoints={[
                                {maxWidth: 'md', cols: 2, spacing: 'md'},
                                {maxWidth: 'sm', cols: 1, spacing: 'sm'},
                            ]}
                        >
                            <Paper {...PAPER_PROPS}>
                                <ThemeIcon {...THEME_ICON_PROPS}>
                                    <IconFolderCode size={24}/>
                                </ThemeIcon>
                                <Title order={4} mt="sm" mb={4}>Modular</Title>
                                <Text fz="sm">All components are built to be used in any combination.</Text>
                            </Paper>
                            <Paper {...PAPER_PROPS}>
                                <ThemeIcon {...THEME_ICON_PROPS}>
                                    <IconSettingsCog size={24}/>
                                </ThemeIcon>
                                <Title order={4} mt="sm" mb={4}>Responsive</Title>
                                <Text fz="sm">Quick is optimized to work for most devices.</Text>
                            </Paper>
                            <Paper {...PAPER_PROPS}>
                                <ThemeIcon {...THEME_ICON_PROPS}>
                                    <IconScaleOutline size={24}/>
                                </ThemeIcon>
                                <Title order={4} mt="sm" mb={4}>Scalable</Title>
                                <Text fz="sm">Remain consistent while developing new features.</Text>
                            </Paper>
                            <Paper {...PAPER_PROPS}>
                                <ThemeIcon {...THEME_ICON_PROPS}>
                                    <IconAdjustmentsHorizontal size={24}/>
                                </ThemeIcon>
                                <Title order={4} mt="sm" mb={4}>Customizable</Title>
                                <Text fz="sm">Change a few variables and the whole theme adapts.</Text>
                            </Paper>
                        </SimpleGrid>
                        <Center mt="lg">
                            <Button
                                size="md"
                                component="a"
                                href="https://analytics-dashboard-docs.netlify.app/"
                                target="_blank"
                                leftIcon={<IconBook size={16}/>}
                            >
                                Read Documentation
                            </Button>
                        </Center>
                    </Container>
                </Box>
                <Box {...BOX_PROPS}>
                    <Paper sx={{backgroundColor: 'transparent', textAlign: 'center'}}>
                        <Title order={3} mb="md">For any queries?</Title>
                        <Button variant="subtle" rightIcon={<IconArrowRight size={16}/>}>Contact Us</Button>
                    </Paper>
                </Box>
            </GuestLayout>
        </>
    )
}
