import React from 'react';
import Head from "next/head";
import {AppLayout} from "@/layout";
import {Anchor, Breadcrumbs, Container, SimpleGrid, Stack, Title} from "@mantine/core";
import {PATH_DASHBOARD} from "@/routes";
import ProjectsData from "../mocks/Projects2.json"
import {ProjectsCard} from "@/components";

const items = [
    {title: 'Dashboard', href: PATH_DASHBOARD.default},
    {title: 'Pages', href: '#'},
    {title: 'Projects', href: '#'},
].map((item, index) => (
    <Anchor href={item.href} key={index}>
        {item.title}
    </Anchor>
));

const ICON_SIZE = 18;

function Projects() {
    const projectItems = ProjectsData.map(p => <ProjectsCard key={p.id} {...p}/>)

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <AppLayout>
                <Container>
                    <Stack>
                        <Title>Projects</Title>
                        <Breadcrumbs>{items}</Breadcrumbs>
                    </Stack>
                    <SimpleGrid cols={3}>
                        {projectItems}
                    </SimpleGrid>
                </Container>
            </AppLayout>
        </>
    );
}

export default Projects;
