import React from "react";
import {Container} from "@mantine/core"
import Head from "next/head";
import {AppLayout} from "@/layout";
import {KanbanBoard} from "@/components";

function Tasks() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <AppLayout>
                <Container>
                    <KanbanBoard/>
                </Container>
            </AppLayout>
        </>
    );
}

export default Tasks
