import React from 'react';
import Head from "next/head";
import {AppLayout} from "@/layout";
import {
    ActionIcon,
    Container,
    Divider,
    Grid,
    Group,
    Paper,
    rem,
    SimpleGrid,
    Stack,
    Text,
    Title,
    useMantineTheme
} from "@mantine/core";
import {IconRefresh} from "@tabler/icons-react";
import {
    FilterDateMenu,
    LanguageTable,
    MapChart,
    MobileDesktopChart,
    SalesChart,
    StatsCard,
    TrafficTable
} from "@/components";
import StatsData from "../../mocks/StatsGrid.json";
import LanguagesData from "../../mocks/Languages.json";
import TrafficData from "../../mocks/Traffic.json";

const PRIMARY_COL_HEIGHT = rem(300);

function Analytics() {
    const theme = useMantineTheme();
    const SECONDARY_COL_HEIGHT = `calc(${PRIMARY_COL_HEIGHT} / 2 - ${theme.spacing.md} / 2)`;

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <AppLayout>
                <Container>
                    <Paper>
                        <Group>
                            <Stack>
                                <Title>Analytics dashboard</Title>
                                <Text>Welcome back, Kelvin! We've missed you. 👋</Text>
                            </Stack>
                            <Group>
                                <ActionIcon>
                                    <IconRefresh/>
                                </ActionIcon>
                                <FilterDateMenu/>
                            </Group>
                        </Group>
                    </Paper>
                    <Divider/>
                    <SimpleGrid cols={2} spacing="md" breakpoints={[{maxWidth: 'sm', cols: 1}]}>
                        <SimpleGrid cols={2}>
                            {StatsData?.data.map(s => <StatsCard key={s.title} data={s}/>)}
                        </SimpleGrid>
                        <MobileDesktopChart/>
                    </SimpleGrid>
                    <Grid>
                        <Grid.Col lg={8}>
                            <MapChart/>
                        </Grid.Col>
                        <Grid.Col lg={4}>
                            <SalesChart/>
                        </Grid.Col>
                        <Grid.Col lg={4}>
                            <LanguageTable data={LanguagesData.slice(0, 6)}/>
                        </Grid.Col>
                        <Grid.Col lg={8}>
                            <TrafficTable data={TrafficData.slice(0, 6)}/>
                        </Grid.Col>
                    </Grid>
                </Container>
            </AppLayout>
        </>
    );
}

export default Analytics;
