import React from 'react';
import Head from "next/head";
import {
    ActionIcon,
    Button,
    Container,
    Divider,
    Grid,
    Group,
    Paper,
    PaperProps,
    Stack,
    Text,
    Title,
} from "@mantine/core";
import {IconChevronRight, IconRefresh} from "@tabler/icons-react";
import {FilterDateMenu, MapChart, ProjectsTable, RevenueChart, SalesChart, StatsGrid} from "@/components";
import StatsData from "../../mocks/StatsGrid.json"
import ProjectsData from "../../mocks/Projects.json"
import {AppLayout} from "@/layout";

const PAPER_PROPS: PaperProps = {
    p: "md",
    shadow: "md",
    radius: "md",
    sx: {height: '100%'}
}

function Saas() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <AppLayout>
                <Container fluid>
                    <Stack spacing="lg">
                        <Paper sx={{backgroundColor: 'transparent'}}>
                            <Group position="apart">
                                <Stack spacing="sm">
                                    <Title order={3}>SaaS dashboard</Title>
                                    <Text>Welcome back, Kelvin!</Text>
                                </Stack>
                                <Group>
                                    <ActionIcon>
                                        <IconRefresh size={18}/>
                                    </ActionIcon>
                                    <FilterDateMenu/>
                                </Group>
                            </Group>
                        </Paper>
                        <Divider/>
                        <StatsGrid data={StatsData.data} paperProps={PAPER_PROPS}/>
                        <Grid>
                            <Grid.Col lg={5}>
                                <MapChart {...PAPER_PROPS}/>
                            </Grid.Col>
                            <Grid.Col lg={7}>
                                <RevenueChart {...PAPER_PROPS}/>
                            </Grid.Col>
                            <Grid.Col lg={4}>
                                <SalesChart {...PAPER_PROPS}/>
                            </Grid.Col>
                            <Grid.Col lg={8}>
                                <Paper {...PAPER_PROPS}>
                                    <Group position="apart" mb="md">
                                        <Text size="lg" fw={600}>Tasks</Text>
                                        <Button variant="subtle" rightIcon={<IconChevronRight size={18}/>}>View all</Button>
                                    </Group>
                                    <ProjectsTable data={ProjectsData.slice(0, 6)}/>
                                </Paper>
                            </Grid.Col>
                        </Grid>
                    </Stack>
                </Container>
            </AppLayout>
        </>
    );
}

export default Saas;
